export const PRODUCT_MODULE_CONFIG = 'ADMIN.PRODUCT.CONFIG'
export const INVENTORY_MODULE_CONFIG = 'ADMIN.INVENTORY.CONFIG'

// model
export const CATEGORY_MODEL = 'INVENTORY.CATEGORY_MODEL'
export const PRODUCT_MODEL = 'INVENTORY.PRODUCT_MODEL'
export const BRAND_MODEL = 'INVENTORY.BRAND_MODEL'
export const MATERIAL_MODEL = 'INVENTORY.MATERIAL_MODEL'

export const SIZE_UNIT = ['cm', 'm', 'mm', 'inch']

export const CATEGORY_EVENTS = {
	OnCreated: 'CATEGORY.CREATED',
	OnUpdated: 'CATEGORY.UPDATED',
	OnDeleted: 'CATEGORY.DELETED',
}

export const PRODUCT_EVENTS = {
	OnCreated: 'PRODUCT.CREATED',
	OnUpdated: 'PRODUCT.UPDATED',
	OnDeleted: 'PRODUCT.DELETED',
}
