export const INVENTORY_MODULE_CONFIG = 'ADMIN.INVENTORY.CONFIG'

// model
export const CAT_MODEL = 'INVENTORY.CAT_MODEL'
export const CATEGORY_MODEL = 'INVENTORY.CATEGORY_MODEL'
export const BRAND_MODEL = 'INVENTORY.BRAND_MODEL'
